= TruffleHog Secret Scan Code Action

This Action integrates TruffleHog, a secret scanning tool, into the CI/CD pipeline to detect secrets and sensitive information in the codebase.
This action provides flexibility by allowing users to either specify a repository URL to scan or scan the currently checked-out code. When given a repository URL, it examines the code directly from the specified repository. Alternatively, if no URL is provided, it defaults to scanning the code present in the local working directory. This dual functionality ensures comprehensive security checks can be performed on both remote and local codebases.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `token`
| string
| No
| The token for authentication.

| `repoUrl`
| string
| No
| The URL of the Git repository to scan. If provided, the scan will be performed against this repository. If not provided, the scan will be performed against the current repository.

| `branch`
| string
| Yes
| The branch of the repository to scan. In case of code scan against the current respository, this should be current branch.

| `path`
| string
| No
| The path of the directory to scan. In case of code scan against custom directory, this should be path pointing to the custom directory. If not provided, the scan will be performed against standard cloudbees workspace directory.

|===

== Usage

To use this action in your workflow, add a step that references it. Here is an example of a workflow that uses the "TruffleHog Secret SAST Action":

* This example shows the usage of scan against given respository url

[source,yaml]
----
on:
  push:
    branches:
      - main    

jobs:
  secret-scan:
    steps:
      - name: Run TruffleHog Secret SAST
        uses: cloudbees-io/trufflehog-secret-actions
        with:
          token: ${{ secrets.TOKEN }}
          repoUrl: ${{ repositoryUrl }}
          branch: ${{ branch }}
----

* This example shows the usage of scan against current checked out code in the pipeline

[source,yaml]
----
on:
  push:
    branches:
      - main

jobs:
  secret-scan:
    steps:
     
     - name: Get sourcecode
        uses: cloudbees-io/checkout@v1

      - name: Run TruffleHog Secret SAST
        uses: cloudbees-io/trufflehog-secret-actions
        with:
          branch: ${{ cloudbees.scm.branch }}
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].