= CloudBees action: Scan code with TruffleHog

Use this action to detect secrets and sensitive information in the codebase with TruffleHog, an open-source secret scanning tool.

This action provides flexibility by allowing users to either scan a local codebase, or provide a URL to scan a remote repository.
When a repository URL is specified, the TruffleHog action examines the code directly from the specified repository.
If no URL is provided, the action scans the code present in the local working directory.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `token`
| string
| No
| The token for authentication.

| `repoUrl`
| string
| No
| The URL of the Git repository to scan.
If `repoUrl` is not specified, the current repository is scanned.

| `branch`
| string
| Yes
| The branch of the repository to scan.
If `repoUrl` is not specified, this must be the current branch.

| `path`
| string
| No
| The path of the directory to scan.
If not specified, the standard CloudBees `workspace` directory is scanned.

| `since-commit`
| string
| No
| The commit hash or branch name to start the scan from.

| `threshold-very-high`
| integer
| No
| The number threshold of very high severity vulnerabilities at which the build is broken.

|===


== Usage examples

Add to your YAML file.

Scan a repository branch:

[source,yaml]
----
      - name: Run TruffleHog code scan
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          token: ${{ secrets.TOKEN }}
          repoUrl: ${{ repositoryUrl }}
          branch: ${{ branch }}
----

Scan a local codebase:

[source,yaml]
----
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Run TruffleHog secret scan on local source code
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          branch: ${{ cloudbees.scm.branch }}
----

Scan the entire history of a local codebase branch:

[source,yaml]
----
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1
        with:
          fetch-depth: 0 # Fetch the full history

      - name: Run TruffleHog scan on full history
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          branch: ${{ cloudbees.scm.branch }}
----

In the following example, if there are more than three very high severity vulnerabilities identified, the build is broken.

[source,yaml]
----

      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Run TruffleHog secret scan with threshold
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          branch: ${{ cloudbees.scm.branch }}
          threshold-very-high: 3
----

Scan a local codebase branch starting from a specified commit hash:

[source,yaml]
----

      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Run TruffleHog starting from commit
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          branch: ${{ cloudbees.scm.branch }}
          since-commit: ${{ commit.hash }}
          threshold-very-high: 3
----

In the following example, a local codebase is scanned from the last commit of the `main` branch up to the latest commit of the current branch.
Fetching the entire history is required for this usage.

[source,yaml]
----

     - name: Check out source code
       uses: cloudbees-io/checkout@v1
       with:
        fetch-depth: 0 # Fetch the full history

     - name: Run TruffleHog scan since a commit
       uses: cloudbees-io/trufflehog-secret-scan-code@v1
       with:
         branch: ${{ cloudbees.scm.branch }} # Current branch
         since-commit: "main" # Scan starting point
         threshold-very-high: 3
----

Scan a given repository from a specified commit hash:

[source,yaml]
----

     - name: Run TruffleHog code scan on a repo
       uses: cloudbees-io/trufflehog-secret-scan-code@v1
       with:
         token: ${{ secrets.TOKEN }}
         repoUrl: ${{ repositoryUrl }}
         branch: ${{ branch }}
         since-commit: ${{ commit.hash }}
----

NOTE: In the example above, if both the `since-commit` and `branch` parameters are set to the same value, the scan detects no changes.

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
